export { service as commonService } from '@/features/common/services/common.service'
export { service as homeService } from '@/features/home/services/home.service'
export { service as userService } from '@/features/user/services/user.service'
export { service as authService } from '@/features/auth/services/auth.service'
export { service as courseService } from '@/features/course/services/course.service'
export { service as modelService } from '@/features/model/services/model.service'
export { service as settingsService } from '@/features/settings/services/settings.service'
